---
name: Deploys
permissions:
  contents: read
  id-token: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        app_name:
          - 001-python-flask
          - 002-node-express
        environment:
          - dev
          - staging
          - prod
    uses: ./.github/workflows/deploy-lambda-app.yml
    with:
      app_name: ${{ matrix.app_name }}
      environment: ${{ matrix.environment }}
    secrets: inherit
