---
name: Deploy Lambda App

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      environment:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: aws
    defaults:
      run:
        working-directory: deployments/${{ inputs.app_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-west-2

      - name: Check access
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ inputs.environment }}/${{ inputs.app_name }}/terraform.tfstate"

      - name: Create ECR repository
        env:
          TF_VAR_environment: ${{ inputs.environment }}
        run: terraform apply -auto-approve -target=module.app.aws_ecr_repository.app

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          TF_VAR_environment: ${{ inputs.environment }}
        run: |
          ECR_URI=$(terraform output -raw ecr_repository_url)
          docker pull $ECR_URI:latest || true
          docker build --cache-from $ECR_URI:latest -t $ECR_URI:${{ github.sha }} -t $ECR_URI:latest ../../${{ inputs.app_name }}
          docker push $ECR_URI:${{ github.sha }}
          docker push $ECR_URI:latest

      - name: Terraform apply
        env:
          TF_VAR_environment: ${{ inputs.environment }}
          TF_VAR_image_tag: ${{ github.sha }}
        run: terraform apply -auto-approve
