---
name: Deploys

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-001-python-flask:
    uses: ./.github/workflows/deploy-lambda-app.yml
    with:
      app_name: 001-python-flask
    secrets: inherit

  deploy-002-node-express:
    uses: ./.github/workflows/deploy-lambda-app.yml
    with:
      app_name: 002-node-express
    secrets: inherit
